#deps
code.o: $(INCDIR)/bits/scc/scc.h
code.o: cc2.h
main.o: $(INCDIR)/bits/scc/arg.h
main.o: $(INCDIR)/bits/scc/scc.h
main.o: cc2.h
main.o: error.h
node.o: $(INCDIR)/bits/scc/scc.h
node.o: cc2.h
optm.o: $(INCDIR)/bits/scc/scc.h
optm.o: cc2.h
parser.o: $(INCDIR)/bits/scc/cstd.h
parser.o: $(INCDIR)/bits/scc/scc.h
parser.o: cc2.h
peep.o: $(INCDIR)/bits/scc/scc.h
peep.o: cc2.h
symbol.o: $(INCDIR)/bits/scc/scc.h
symbol.o: cc2.h
amd64-sysv/cgen.o: $(INCDIR)/bits/scc/scc.h
amd64-sysv/cgen.o: amd64-sysv/../cc2.h
amd64-sysv/cgen.o: amd64-sysv/arch.h
amd64-sysv/code.o: $(INCDIR)/bits/scc/cstd.h
amd64-sysv/code.o: $(INCDIR)/bits/scc/scc.h
amd64-sysv/code.o: amd64-sysv/../cc2.h
amd64-sysv/code.o: amd64-sysv/arch.h
amd64-sysv/optm.o: $(INCDIR)/bits/scc/scc.h
amd64-sysv/optm.o: amd64-sysv/../cc2.h
amd64-sysv/types.o: $(INCDIR)/bits/scc/scc.h
amd64-sysv/types.o: amd64-sysv/../cc2.h
arm64-sysv/types.o: $(INCDIR)/bits/scc/scc.h
arm64-sysv/types.o: arm64-sysv/../cc2.h
i386-sysv/cgen.o: $(INCDIR)/bits/scc/scc.h
i386-sysv/cgen.o: i386-sysv/../cc2.h
i386-sysv/cgen.o: i386-sysv/arch.h
i386-sysv/code.o: $(INCDIR)/bits/scc/cstd.h
i386-sysv/code.o: $(INCDIR)/bits/scc/scc.h
i386-sysv/code.o: i386-sysv/../cc2.h
i386-sysv/code.o: i386-sysv/arch.h
i386-sysv/optm.o: $(INCDIR)/bits/scc/scc.h
i386-sysv/optm.o: i386-sysv/../cc2.h
i386-sysv/types.o: $(INCDIR)/bits/scc/scc.h
i386-sysv/types.o: i386-sysv/../cc2.h
qbe/cgen.o: $(INCDIR)/bits/scc/cstd.h
qbe/cgen.o: $(INCDIR)/bits/scc/scc.h
qbe/cgen.o: qbe/../cc2.h
qbe/cgen.o: qbe/arch.h
qbe/code.o: $(INCDIR)/bits/scc/cstd.h
qbe/code.o: $(INCDIR)/bits/scc/scc.h
qbe/code.o: qbe/../cc2.h
qbe/code.o: qbe/arch.h
qbe/optm.o: $(INCDIR)/bits/scc/scc.h
qbe/optm.o: qbe/../cc2.h
z80-scc/cgen.o: $(INCDIR)/bits/scc/scc.h
z80-scc/cgen.o: z80-scc/../cc2.h
z80-scc/cgen.o: z80-scc/arch.h
z80-scc/code.o: $(INCDIR)/bits/scc/cstd.h
z80-scc/code.o: $(INCDIR)/bits/scc/scc.h
z80-scc/code.o: z80-scc/../cc2.h
z80-scc/code.o: z80-scc/arch.h
z80-scc/optm.o: $(INCDIR)/bits/scc/scc.h
z80-scc/optm.o: z80-scc/../cc2.h
z80-scc/types.o: $(INCDIR)/bits/scc/scc.h
z80-scc/types.o: z80-scc/../cc2.h
